#! /bin/sh
exec ruby -S -x "$0" "$@"
#! ruby

require 'optparse'
params = ARGV.getopts("n:","t:")
 
class Template < Struct.new(:name)
end

class ProjectGenerator < Struct.new(:target_dir,:project_name,:template)
	def generate
		code_dir = File::dirname(Dir::pwd+"/"+__FILE__)
		template_dir = code_dir + "/tmp/" + template.name + "/"
		begin
			system("mkdir #{project_name}")
			system("cp #{template_dir}/* #{target_dir}/#{project_name} -r")
		rescue
		end
	end
end

if params["t"] == nil
	params["t"] = "default"
end

project_generator = ProjectGenerator.new(Dir::pwd, params["n"], Template.new(params["t"])).generate
