#! /bin/sh
exec ruby -S -x "$0" "$@"
#! ruby
#
require 'optparse'
opt = OptionParser.new
# params = ARGV.getopts("t:f:", "foo", "bar:")
params = ARGV.getopts("n:","t:")
p params
# p params["t"]
# p params["f"]
 
class Template < Struct.new(:name)
end

class ProjectGenerator < Struct.new(:target_dir,:project_name,:template)
	def generate
		code_dir = File::dirname(Dir::pwd+"/"+__FILE__)
		p code_dir
		
		template_dir = code_dir + "/tmp/" + template.name + "/"
		p template_dir
		
		p target_dir
		
		begin
			system("mkdir #{project_name}")
			system("cp #{template_dir}/* #{target_dir}/#{project_name} -r")
		rescue
		end
	end
end

if params["t"] == nil
	params["t"] = "default"
end

project_generator = ProjectGenerator.new(Dir::pwd, params["n"], Template.new(params["t"]))
project_generator.generate
